### ISSUE TITLE
What is the default username and password?

### ISSUE THREAD

**Issue by kujiy** [visualive/va-simple-basic-auth#5]
I installed, activated and logout. Then it started to work and I never get login.

**Comment by kuck1u** [comment]
@kujiy 

Hi.

Please read the description of the plugin page.
[https://wordpress.org/plugins/va-simple-basic-auth/](https://wordpress.org/plugins/va-simple-basic-auth/)

![_2016-10-05_9_22_41](https://cloud.githubusercontent.com/assets/7222225/19097249/058fcc98-8ade-11e6-86d9-43a16be0271b.png)

**Comment by kujiy** [comment]
Thanks! I'm sorry I'm a new for wordpress. It's easy to install most of plugins but seem to be difficult what can do next. I hope you write it in also Installation page 👍
