### ISSUE TITLE
Wordpress API

### ISSUE THREAD

**Issue by Lobosque** [visualive/va-simple-basic-auth#6]
Did you test this with the new Wordpress 4.7 API? It did not work for me.

**Comment by kuck1u** [comment]
In my environment it works without problems.

2016/12/09 午前0:14 "Lucas Lobosque" <notifications@github.com>:

**Comment by mmousa8189** [comment]
@kuck1u  Please help me [Screenshot](https://www.mediafire.com/view/3x8709bnop3m57d/xxxs.png)
this dialog after install plugin

**Comment by kuck1u** [comment]
GoTo https://github.com/visualive/va-simple-basic-auth/issues/5
